<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        <?php require_once 'css/styles.css' ?>
    </style>
</head>
<body>
<?php
    echo "<h1>Registrarse</h1>";
    echo "<h3>Ya tienes una cuenta? <a href='index.php'>Inicia sesión</a></h3>";
    echo '<form method="post" action="index.php">
            <input type="text" name="username" placeholder="Nombre de usuario" required><br>
            <input type="password" name="password" placeholder="Contraseña" required><br>
            <input type="submit" value="Registrarse">
            </form>';
?>
</body>
</html>
